name: test-list-view-jest
run-name: ${{ github.actor }} is testing code
on: [push]
jobs:
  testing-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '21.4.0'
      - run: npm test      
